name: Cache Bust Everything

on:
  push:
    branches: ["main"]

jobs:
  bust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Add timestamp to all assets
        run: |
          TS=$(date +%s)

          # File types to bust (add more if needed)
          exts="css js png jpg jpeg ico svg gif webp"

          for ext in $exts; do
            for f in *.$ext; do
              [ -f "$f" ] || continue
              NEW="${f%.*}.$TS.${f##*.}"
              mv "$f" "$NEW"
              # Update references in ALL html/css/js files
              grep -rl "$f" . --include \*.html --include \*.css --include \*.js | xargs sed -i "s|$f|$NEW|g"
            done
          done

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "Auto cache-bust"
          git push
